name: SonarCloud Analysis

on: pull_request

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: mvn clean install -DskipTests

      - run: mvn sonar:sonar 
          -Dsonar.projectKey=githubact
          -Dsonar.organization=githubact
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
